In [1]:
import random

In [2]:
salary_list = [random.randint(50000, 150000) for _ in range(1_000_000)]

In [3]:
salary_list

[101659,
 146579,
 109892,
 130646,
 83494,
 125086,
 138703,
 86630,
 137111,
 73785,
 135460,
 108504,
 145053,
 64337,
 124098,
 115775,
 63838,
 105453,
 136682,
 51702,
 125459,
 95739,
 88066,
 136869,
 61730,
 60916,
 53746,
 114096,
 98269,
 72931,
 115936,
 64352,
 91249,
 133664,
 61525,
 118759,
 62458,
 128647,
 123740,
 133056,
 134051,
 144117,
 70562,
 93537,
 64535,
 133660,
 80600,
 142314,
 63829,
 118278,
 71331,
 137590,
 78869,
 65160,
 146815,
 91041,
 55764,
 100662,
 128464,
 77694,
 99877,
 66547,
 132751,
 146456,
 59322,
 122297,
 128530,
 114421,
 120016,
 65698,
 123457,
 131492,
 140743,
 68383,
 118436,
 73547,
 69124,
 144457,
 119037,
 99690,
 56204,
 105720,
 136630,
 98126,
 51779,
 68765,
 122331,
 138694,
 123229,
 88504,
 53103,
 143741,
 74532,
 138727,
 63907,
 85265,
 73972,
 125632,
 108641,
 131571,
 108051,
 86798,
 62561,
 143697,
 138344,
 137490,
 99768,
 79315,
 79652,
 61723,
 143387,
 118514,
 56884,
 90049,
 117106,
 139228,
 59425,
 8

In [4]:
import statistics

In [5]:
%%timeit

statistics.mean(salary_list)

330 ms ± 77.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
import numpy as np

In [7]:
%%timeit

np.mean(salary_list)

93.5 ms ± 44.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
my_array = np.array([1, 2, 3, 4])

In [9]:
float(my_array.mean())

2.5

In [10]:
job_titles = np.array(['Data Engineer', 'Data Analyst', 'Financial Analyst', 'Data Scientist', 'AI Engineer'])

base_salaries = np.array([40000, 35000, 58000, 39000, np.nan])

bonus_rates = np.array([.1, .25, .12, .5, np.nan])

In [11]:
total_salaries = base_salaries * (1 + bonus_rates)

total_salaries

array([44000., 43750., 64960., 58500.,    nan])

In [12]:
np.nanmean(total_salaries)

np.float64(52802.5)

In [13]:
float(np.nanmean(total_salaries))

52802.5

In [14]:
type(None)

NoneType

In [15]:
type(np.nan)

float

In [16]:
base_salaries_plus_ten = base_salaries + 10

In [17]:
base_salaries_plus_ten

array([40010., 35010., 58010., 39010.,    nan])

In [18]:
fourth_and_fifth_job_titles = job_titles[3:5]

In [19]:
fourth_and_fifth_job_titles

array(['Data Scientist', 'AI Engineer'], dtype='<U17')

In [20]:
jobs_with_more_than_point_one_bonus = job_titles[bonus_rates > .1]

In [21]:
jobs_with_more_than_point_one_bonus

array(['Data Analyst', 'Financial Analyst', 'Data Scientist'],
      dtype='<U17')

In [23]:
 cumulative_sum_array = np.cumsum(base_salaries_plus_ten)

In [24]:
cumulative_sum_array

array([ 40010.,  75020., 133030., 172040.,     nan])

In [25]:
base_salary_std_dev = np.std(base_salaries)

In [26]:
base_salary_std_dev

np.float64(nan)

In [27]:
new_base_salary = base_salaries[:-1]

In [28]:
new_base_salary

array([40000., 35000., 58000., 39000.])

In [29]:
new_base_salary_std_dev = np.std(new_base_salary)

In [31]:
float(new_base_salary_std_dev)

8860.022573334676